enhance(get): Allow setting a default value on Config::get()
roots/wp-config pull request #13
Opened 2020-04-14 03:49 UTC by Log1x

2020-04-14 04:41 UTC, austinpray requested changes
added some failing test cases 5244479b5de644dabba3b6190a7c28326618b789

2020-04-14 04:47 UTC, austinpray commented on tests/ConfigTest.php
> +    $this->assertEquals(1, Config::get('BRANDON', 1));
```suggestion
    $this->assertEquals(1, Config::get('BRANDON', 1));
    $this->assertEquals(0, Config::get('BRANDON', 0));
```

![image](https://user-images.githubusercontent.com/2192970/79187162-2fb92d80-7de1-11ea-82f0-7f5511e9dcef.png)

2025-01-30 00:38 UTC, tangrufus commented
Discussion: If `Config::get()` returns default values, do we still need `UndefinedConfigKeyException`?

In my opinion, since we always have a default value (`$default = null`), we never need to throw `UndefinedConfigKeyException`.
If users really need to check whether a key is defined in the [`configMap`](https://github.com/roots/wp-config/blob/629c53313276c8f06d4e471a0858c4fe583aa058/src/Config.php#L18), we can add a `Config::has()` method.

2026-03-10 23:33 UTC, retlehs commented
Resolved by #20

2026-03-10 23:33 UTC, closed without merging